services:
  - type: web
    name: dermascan-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health

